{
    "name": "Custom_layouts_models_ILDO_OIL",
    "version": "1.1.0",
    "category": "Tools",
    "summary": "Agencements personnalisés pour les documents PDF",
    "description": "Ajoute de nouveaux agencements pour les factures, devis, bons, etc.",
    "author": "Alain GANSONRE",
    "depends": ["base", "sale", "sale_stock", "web", "account", "account_reports", "uom", "purchase", "stock"],
    "external_dependencies": {"python": ["num2words"]},
    "data": [
        'security/ir.model.access.csv',
        'data/paperformat_no_header.xml',
        'data/third_party_balance_report.xml',
        'views/res_partner_views.xml',
        'views/payment_receipt_professional.xml',
        'views/account_move_views.xml',
        'views/sale_order_views.xml',
        'views/stock_picking_views.xml',
        'views/res_config_settings_views.xml',
        'views/product_template_views.xml',
        'views/external_layouts.xml',
        'views/contenue_principale.xml',
        'views/contenue_principale_sale.xml',
        'views/contenue_principale_purchase.xml',
        'views/contenue_principale_purchasequotation.xml',
        'views/invoice_global_report.xml',
        'views/report_invoice_hide.xml',
        'views/purchase_hide_totals.xml',
        'views/report_sale_hide.xml',
        'views/purchase_hide_fields.xml',
        'views/custom_stock_report.xml',
        'views/contenue_principale_stock.xml',
        'views/payment_list_action.xml',
        'views/payment_list_wizard_views.xml',
        'views/list_print_metadata.xml',
        'views/payment_list_report.xml',
        'views/invoice_list_report.xml',
        'views/invoice_list_action.xml',
        'views/sale_list_action.xml',
        'views/sale_list_report.xml',
        'views/purchase_list_action.xml',
        'views/purchase_list_report.xml',
        'views/stock_list_action.xml',
        'views/stock_list_report.xml',
        'views/report_invoice_hide_payments.xml',
        'views/report_picking_custom.xml',
        'views/stock_menu_inherit.xml',
        'data/report_layouts.xml',
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}
