from . import res_partner
from . import res_company
from . import res_config_settings
from . import account_move
from . import account_payment
from . import payment_list_wizard
from . import quantity_to_words
from . import sale_order
from . import stock_picking
from . import third_party_balance_report
